using './main.bicep'

param vnetName = ''
param apimName = ''
param applicationInsightsName = ''
param logAnalyticsWorkspaceName = ''
param publisherEmail = ''
param publisherName = ''
param keyVaultName = ''
param privateEndpointKeyVaultName = ''
param ptuAOAIName = ''
param paygAOAIName = ''
param privateEndpointPTUName = ''
param privateEndpointPaygName = ''
param vmName = ''
param vmUsername = ''
param vmPassword = ''
param eventHubNamespaceName = ''
param eventHubName = ''
param privateEventHubEndpointName = ''
param privateEventHubFuncAPIMLoggerName = ''
param functionName = ''

